version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: speedcar_web
    restart: always
    volumes:
      - .:/var/www/html
